### PR TITLE
Show ENS name if user owned one

### LINKED ISSUE #43: Show ENS name if user owned one
It would be great if we show the ENS name and avatar if the user has it

image

### PR DESCRIPTION
**Pull request by sasicodes**
## Description

Shown the ENS name of the user if they owned one.

- no new lib installed
- Added `useENS` hook

Fixes #43 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

image

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Added image if it is a UI change

### CODE REVIEW

**Comment by sasicodes** [comment]
cc @alexisgauba

**Comment by alexisgauba** [comment]
Hmm not showing up for me on the deploy preview - is it showing up for you there?

**Comment by sasicodes** [comment]
> Hmm not showing up for me on the deploy preview - is it showing up for you there?

Nope. I tested in local, it working fine with the given keys.

@alexisgauba Netlify much has an environment of infura project id, do we need to rebuild? Any idea?

**Comment by sasicodes** [comment]
@alexisgauba 
image

**Review by alexisgauba — APPROVED** [review]

**Pull request merged**
